### ISSUE TITLE
Wiki get_all_links error

### ISSUE THREAD

**Issue by joshash** [hardikvasa/webb#5]
Hi, whenever I try to crawl a page a wiki page and download links, I get the following error:
```
Link = https://en.wikipedia.org/wiki/Lucid_dream
Traceback (most recent call last):
  File "/Users/ashkij/Documents/Programming/Python Stuff/untitled5", line 3, in <module>
    print(webb.wikipedia_crawl('https://en.wikipedia.org/wiki/Lucid_dream?oldformat=true',100, 'animal_collective.txt'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/webb/webb.py", line 859, in wikipedia_crawl
    to_crawl = to_crawl + get_all_links(raw_html)
NameError: name 'get_all_links' is not defined 
```

And indeed, when I open up webb.py and go to line 859 `get_all_links` is never defined. How do I fix this? Or is there a more recent webb.py file?

**Comment by hardikvasa** [comment]
@joshash are you referring to the newer version of the repository from Github?

I myself installed the newer version from Github and tested it on my local machine with the command similar to yours:

    from webb import webb

    print(webb.wikipedia_crawl('https://en.wikipedia.org/wiki/Lucid_dream?oldformat=true',100, 'animal_collective.txt'))


and it worked just fine. It did crawl 100 pages and stored the logs into the text file. The `wikipedia_crawl` function in newer version refers to `find_all_links()` instead of `get_all_links()`.
